"""
API route handlers for chat interactions with Server-Sent Events (SSE) streaming.

This module provides the /chat/stream endpoint that returns streaming responses
using SSE for real-time token generation from the LLM.
"""

from __future__ import annotations

import asyncio
import json
import uuid
from datetime import datetime
from typing import Any, AsyncGenerator, Dict, Optional

from fastapi import APIRouter, Request, status
from fastapi.responses import StreamingResponse
from loguru import logger
from pydantic import ValidationError

from entrypoints.api.schemas import ChatRequest, ChatResponseChunk


router = APIRouter()


async def generate_chat_stream(
    request: ChatRequest,
    conversation_id: str,
    request_id: str,
) -> AsyncGenerator[str, None]:
    """
    Generate streaming chat response chunks using Server-Sent Events format.

    This is a mock implementation that simulates LLM token streaming.
    In production, this would connect to the actual LangGraph agent.

    Args:
        request: The validated chat request.
        conversation_id: Unique identifier for the conversation.
        request_id: Unique identifier for this specific request.

    Yields:
        str: SSE-formatted message chunks.

    Raises:
        Exception: Logs any errors during stream generation.
    """
    try:
        # Simulate LLM processing delay
        await asyncio.sleep(0.1)

        # Mock response - in production, this comes from LangGraph agent
        mock_response = (
            f"Hello! I received your message: '{request.message}'. "
            f"This is a simulated streaming response from the Agentic AI system. "
            f"In production, this would be generated by the LangGraph agent with RAG capabilities."
        )

        # Split response into chunks for streaming simulation
        words = mock_response.split()
        chunk_size = 3  # Number of words per chunk

        for i in range(0, len(words), chunk_size):
            chunk_words = words[i : i + chunk_size]
            chunk_text = " ".join(chunk_words)

            response_chunk = ChatResponseChunk(
                chunk=chunk_text + " ",
                conversation_id=conversation_id,
                is_last=False,
                metadata={
                    "chunk_index": i // chunk_size,
                    "timestamp": datetime.utcnow().isoformat(),
                    "request_id": request_id,
                },
            )

            # Format as SSE message
            sse_message = f"data: {response_chunk.model_dump_json()}\n\n"
            yield sse_message

            # Simulate token generation delay
            await asyncio.sleep(0.05)

        # Send final chunk
        final_chunk = ChatResponseChunk(
            chunk="",
            conversation_id=conversation_id,
            is_last=True,
            metadata={
                "total_chunks": (len(words) + chunk_size - 1) // chunk_size,
                "timestamp": datetime.utcnow().isoformat(),
                "request_id": request_id,
            },
        )

        sse_final = f"data: {final_chunk.model_dump_json()}\n\n"
        yield sse_final

        logger.info(
            "stream_complete",
            request_id=request_id,
            conversation_id=conversation_id,
            total_chunks=(len(words) + chunk_size - 1) // chunk_size,
        )

    except Exception as e:
        logger.error(
            "stream_error",
            request_id=request_id,
            conversation_id=conversation_id,
            error_type=type(e).__name__,
            error_message=str(e),
            exc_info=True,
        )
        # Send error chunk
        error_chunk = ChatResponseChunk(
            chunk=f"[Error: {str(e)}]",
            conversation_id=conversation_id,
            is_last=True,
            metadata={"error": True},
        )
        yield f"data: {error_chunk.model_dump_json()}\n\n"


@router.post("/chat/stream")
async def chat_stream(
    request: ChatRequest,
    req: Request,
) -> StreamingResponse:
    """
    Handle chat requests with streaming responses via Server-Sent Events.

    This endpoint accepts a chat message and returns a streaming response
    where tokens are sent as they are generated by the LLM.

    Args:
        request: Validated ChatRequest containing the user's message.
        req: FastAPI Request object for extracting metadata.

    Returns:
        StreamingResponse: SSE stream of ChatResponseChunk objects.

    Raises:
        HTTPException: If request validation fails.
    """
    # Extract request ID from middleware or generate new one
    request_id = getattr(req.state, "request_id", str(uuid.uuid4()))
    conversation_id = request.conversation_id or f"conv_{uuid.uuid4().hex[:8]}"

    logger.info(
        "chat_request_started",
        request_id=request_id,
        conversation_id=conversation_id,
        session_id=request.session_id,
        message_length=len(request.message),
        has_metadata=request.metadata is not None,
    )

    try:
        # Validate request using Pydantic
        validated_request = ChatRequest.model_validate(request.model_dump())

        logger.debug(
            "request_validated",
            request_id=request_id,
            conversation_id=conversation_id,
        )

        # Create streaming response
        return StreamingResponse(
            generate_chat_stream(
                request=validated_request,
                conversation_id=conversation_id,
                request_id=request_id,
            ),
            media_type="text/event-stream",
            headers={
                "X-Request-ID": request_id,
                "X-Conversation-ID": conversation_id,
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            },
        )

    except ValidationError as e:
        logger.warning(
            "chat_validation_error",
            request_id=request_id,
            errors=e.errors(),
        )
        raise

    except Exception as e:
        logger.error(
            "chat_unexpected_error",
            request_id=request_id,
            conversation_id=conversation_id,
            error_type=type(e).__name__,
            error_message=str(e),
            exc_info=True,
        )
        raise


@router.post("/chat/complete")
async def chat_complete(
    request: ChatRequest,
    req: Request,
) -> Dict[str, Any]:
    """
    Handle chat requests with non-streaming (complete) responses.

    This endpoint is provided for clients that don't support streaming.
    It waits for the complete response before returning.

    Args:
        request: Validated ChatRequest containing the user's message.
        req: FastAPI Request object for extracting metadata.

    Returns:
        dict: Complete response with full message content.
    """
    request_id = getattr(req.state, "request_id", str(uuid.uuid4()))
    conversation_id = request.conversation_id or f"conv_{uuid.uuid4().hex[:8]}"

    logger.info(
        "chat_complete_request",
        request_id=request_id,
        conversation_id=conversation_id,
    )

    # Collect all chunks from the stream generator
    full_response = ""
    async for chunk_data in generate_chat_stream(
        request=request,
        conversation_id=conversation_id,
        request_id=request_id,
    ):
        if chunk_data.startswith("data: "):
            try:
                chunk_json = chunk_data[6:].strip()
                chunk_obj = json.loads(chunk_json)
                if not chunk_obj.get("is_last", False):
                    full_response += chunk_obj.get("chunk", "")
            except json.JSONDecodeError:
                continue

    return {
        "conversation_id": conversation_id,
        "message": full_response.strip(),
        "request_id": request_id,
        "timestamp": datetime.utcnow().isoformat(),
    }
